import { ProductI } from "@/types/product";

export const productColumnOptions: { key: keyof ProductI; label: string }[] = [
  { key: "name", label: "Nombre" },
  { key: "description", label: "Descripción" },
  { key: "internal_code", label: "Código interno" }, 
  { key: "category", label: "Categoría" },
  { key: "brand", label: "Marca" },
  { key: "current_quantity", label: "Cantidad" },
  { key: "min_stock", label: "Stock Mínimo" },
  { key: "max_stock", label: "Stock Máximo" },
  { key: "unit_of_measure", label: "Unidad" },
  { key: "purchase_price", label: "Precio Compra" },
  { key: "sale_price", label: "Precio Venta" },
  { key: "profit_margin", label: "Margen Ganancia" },
  { key: "entry_date", label: "Fecha Entrada" },
  { key: "last_updated", label: "Última Actualización" },
  { key: "image", label: "Imagen" },
  { key: "sales_frequency", label: "Frecuencia Ventas" },
  { key: "isActive", label: "Activo" },
  { key: "isPerishable", label: "Perecedero" },
  { key: "expiration_date", label: "Fecha Expiración" },
  { key: "notes", label: "Notas" },
  { key: "current_trend", label: "Tendencia" },
  { key: "createdBy", label: "Creado por" },
  { key: "updatedBy", label: "Actualizado por" },
  { key: "last_purchase_date", label: "Últ. compra" },
  { key: "last_sale_date", label: "Últ. venta" },
];
